"""initial tables

Revision ID: 212ab838d306
Revises: 
Create Date: 2026-03-26 09:43:32.221118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '212ab838d306'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('startup_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('mrr_usd', sa.Float(), nullable=True),
    sa.Column('burn_rate_usd', sa.Float(), nullable=True),
    sa.Column('runway_months', sa.Float(), nullable=True),
    sa.Column('headcount', sa.Integer(), nullable=True),
    sa.Column('has_cto', sa.Boolean(), nullable=True),
    sa.Column('dev_spend_pct', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('startup_profiles')
    # ### end Alembic commands ###
